path_root <- here::here()
path_data_root <- here::here("data")
path_data_raw <- fs::path(path_data_root, "raw")
path_analysis_root <- here::here("analysis")
path_figures_folder <- fs::path(path_analysis_root, "figures")
path_tables_folder <- fs::path(path_analysis_root, "tables")
path_pdfs_folder <- fs::path(path_analysis_root, "pdfs")
path_reports_folder <- fs::path(path_analysis_root, "reports")
path_script_root <- here::here("script")
path_script_R <- fs::path(path_script_root, "R_script")
path_script_stata <- fs::path(path_script_root, "stata_do")
path_presentations_root <- here::here("presentations")
path_r_objects <- here::here("R")
path_support_files <- here::here("support_files")
